nav:
  Home: https://huqianshan.github.io
  About: https://github.com/huqianshan/huqianshan.github.io
  DouBan: https://www.douban.com/people/170755953/
  Projects: https://github.com/huqianshan
  Search: https://huqianshan.github.io/Search/
 

projects_url: https://github.com/huqianshan

customize:
    gravatar:
        email: 1196455147@qq.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/huqianshan
        weixin: /
        qq: /
        book: /     
        film: /
    show_all_posts: true
    post_count: 5
    highlight: darkula

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: huqianshan
    google_analytics: UA-113512264-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
        
